---
- name: Install nginx and web dependencies
  yum: name={{ item }}
  with_items:
   - nginx-1.6.0
   # - mod_ssl

- name: Disable apache service
  service: name=httpd state=stopped enabled=no
  ignore_errors: yes

- name: Remove default nginx config file
  file: path=/etc/nginx/conf.d/default.conf state=absent
  notify: restart nginx

- name: Copy nginx config file
  template: src=webapp.conf dest=/etc/nginx/conf.d
  notify: restart nginx

- name: Set nginx service state
  service: name=nginx state=started enabled=yes

- name: Set user home e(+x)ecution permission to allow nginx access
  file: path=/home/{{ ansible_ssh_user }} mode=701
  # shell: chmod o+x ~

- name: Create folder to deploy the app
  file: path=/home/{{ ansible_ssh_user }}/apps/webapp/current state=directory
  sudo: no